# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ranking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ranking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rranking.proto\x12\x16io.github.gvn2012.grpc\"Z\n\x0eRankingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x37\n\ncandidates\x18\x02 \x03(\x0b\x32#.io.github.gvn2012.grpc.PostFeature\"\xa0\x01\n\x0bPostFeature\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x11\n\tauthor_id\x18\x02 \x01(\t\x12\x17\n\x0f\x61uthor_affinity\x18\x03 \x01(\x01\x12\x16\n\x0evelocity_score\x18\x04 \x01(\x01\x12\x15\n\rrecency_hours\x18\x05 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x06 \x01(\t\x12\x13\n\x0bmedia_count\x18\x07 \x01(\x05\"a\n\x0fRankingResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12=\n\x11ranked_candidates\x18\x02 \x03(\x0b\x32\".io.github.gvn2012.grpc.RankedPost\",\n\nRankedPost\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x01\x32n\n\x0eRankingService\x12\\\n\tRankPosts\x12&.io.github.gvn2012.grpc.RankingRequest\x1a\'.io.github.gvn2012.grpc.RankingResponseB0\n\x1eio.github.gvn2012.grpc.rankingB\x0cRankingProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ranking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036io.github.gvn2012.grpc.rankingB\014RankingProtoP\001'
  _globals['_RANKINGREQUEST']._serialized_start=41
  _globals['_RANKINGREQUEST']._serialized_end=131
  _globals['_POSTFEATURE']._serialized_start=134
  _globals['_POSTFEATURE']._serialized_end=294
  _globals['_RANKINGRESPONSE']._serialized_start=296
  _globals['_RANKINGRESPONSE']._serialized_end=393
  _globals['_RANKEDPOST']._serialized_start=395
  _globals['_RANKEDPOST']._serialized_end=439
  _globals['_RANKINGSERVICE']._serialized_start=441
  _globals['_RANKINGSERVICE']._serialized_end=551
# @@protoc_insertion_point(module_scope)
