package io.github.gvn2012.org_service.entities.enums;

public enum OrgAuditAction {
    ORG_CREATED,
    ORG_UPDATED,
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    TEAM_CREATED,
    TEAM_UPDATED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    POSITION_CREATED,
    POSITION_UPDATED,
    POLICY_PUBLISHED,
    ANNOUNCEMENT_PUBLISHED,
    INVITATION_SENT,
    INVITATION_ACCEPTED,
    JOB_TITLE_CREATED,
    JOB_TITLE_UPDATED,
    JOB_LEVEL_CREATED,
    JOB_LEVEL_UPDATED,
    SKILL_DEFINITION_CREATED,
    SKILL_DEFINITION_UPDATED
}
