spring.application.name=uploading-service
eureka.client.enabled=false
eureka.instance.enabled=false
spring.cloud.discovery.enabled=false
spring.cloud.loadbalancer.enabled=false

server.port=8090

logging.level.org.mongodb.driver=ERROR
logging.level.org.springframework.data.mongodb=ERROR
spring.data.mongodb.uri=mongodb+srv://vietpt124010122002_db_user:TdgCjxj0PMJDG1Iy@synciocluster.mlgvysv.mongodb.net/?appName=SyncIOCluster
spring.data.mongodb.database=uploading_service

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
management.zipkin.tracing.endpoint=${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://syncio-zipkin:9411/api/v2/spans}
springdoc.api-docs.path=/api/v1/notifications/v3/api-docs

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.spring.web.client.request=true
management.metrics.distribution.percentiles-histogram.spring.web.client.response=true
management.metrics.distribution.percentiles-histogram.spring.cloud.gateway.requests = true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=uploading-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true
