version: "3.9"

services:
  auth-mysql:
    image: mysql:8.4
    container_name: auth-mysql
    environment:
      MYSQL_DATABASE: auth_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - auth_mysql_data:/var/lib/mysql
    networks:
      - syncio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-mysql:
    image: mysql:8.4
    container_name: user-mysql
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - user_mysql_data:/var/lib/mysql
    networks:
      - syncio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  friend-mysql:
    image: mysql:8.4
    container_name: friend-mysql
    environment:
      MYSQL_DATABASE: friend_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3309:3306"
    volumes:
      - friend_mysql_data:/var/lib/mysql
    networks:
      - syncio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  post-mysql:
    image: mysql:8.4
    container_name: post-mysql
    environment:
      MYSQL_DATABASE: post_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3310:3306"
    volumes:
      - post_mysql_data:/var/lib/mysql
    networks:
      - syncio-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10


  notification-mongo:
    image: mongo:7.0
    container_name: notification-mongo
    command: [ "mongod", "--quiet" ]
    ports:
      - "27017:27017"
    volumes:
      - notification_mongo_data:/data/db
    networks:
      - syncio-network
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.runCommand({ ping: 1 })'" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - syncio-network

  discovery-service:
    build:
      context: .
      dockerfile: discovery_service/Dockerfile
    develop:
      watch:
        - path: discovery_service
          action: rebuild
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: discovery-service
      SERVER_PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: discovery-service
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      zipkin:
        condition: service_started
    networks:
      - syncio-network

  auth-service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    develop:
      watch:
        - path: auth_service
          action: rebuild
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_APPLICATION_NAME: auth-service
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-mysql:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      auth-mysql:
        condition: service_healthy
      discovery-service:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - syncio-network

  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    develop:
      watch:
        - path: user_service
          action: rebuild
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_NAME: user-service
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://user-mysql:3306/user_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      user-mysql:
        condition: service_healthy
      discovery-service:
        condition: service_started
      auth-service:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - syncio-network

  friend-service:
    build:
      context: .
      dockerfile: friend_service/Dockerfile
    develop:
      watch:
        - path: friend_service
          action: rebuild
    container_name: friend-service
    ports:
      - "8084:8084"
    environment:
      SPRING_APPLICATION_NAME: friend-service
      SERVER_PORT: 8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://friend-mysql:3306/friend_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      friend-mysql:
        condition: service_healthy
      discovery-service:
        condition: service_started
      auth-service:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - syncio-network

  post-service:
    build:
      context: .
      dockerfile: post_service/Dockerfile
    develop:
      watch:
        - path: post_service
          action: rebuild
    container_name: post-service
    ports:
      - "8085:8085"
    environment:
      SPRING_APPLICATION_NAME: post-service
      SERVER_PORT: 8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://post-mysql:3306/post_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      post-mysql:
        condition: service_healthy
      discovery-service:
        condition: service_started
      auth-service:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - syncio-network

  notification-service:
    build:
      context: .
      dockerfile: notification_service/Dockerfile
    develop:
      watch:
        - path: notification_service
          action: rebuild
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      SPRING_APPLICATION_NAME: notification-service
      SERVER_PORT: 8083
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      SPRING_DATA_MONGODB_URI: mongodb://notification-mongo:27017/notification_db
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      notification-mongo:
        condition: service_healthy
      discovery-service:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - syncio-network

  api-gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    develop:
      watch:
        - path: api_gateway
          action: rebuild
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: api_gateway
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka/
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
      DISCOVERY_SERVICE_UI_URL: http://discovery-service:8761
      MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      discovery-service:
        condition: service_started
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      friend-service:
        condition: service_started
      post-service:
        condition: service_started
      notification-service:
        condition: service_started
      zipkin:
        condition: service_started
    networks:
      - syncio-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - syncio-network
    depends_on:
      discovery-service:
        condition: service_started
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      notification-service:
        condition: service_started
      api-gateway:
        condition: service_started


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - syncio-network
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      prometheus:
        condition: service_started



networks:
  syncio-network:
    driver: bridge

volumes:
  auth_mysql_data:
  user_mysql_data:
  friend_mysql_data:
  post_mysql_data:
  notification_mongo_data:
  prometheus_data:
  grafana_data:
