apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/component: notifications-controller
    app.kubernetes.io/name: argocd-notifications-controller
    app.kubernetes.io/part-of: argocd
data:
  service.webhook.telegram: |
    url: https://api.telegram.org/bot$telegram-bot-token/sendMessage
    headers:
      - name: Content-Type
        value: application/json

  template.telegram-sync-succeeded: |
    webhook:
      telegram:
        method: POST
        body: |
          {
            "chat_id": "7537927055",
            "parse_mode": "HTML",
            "text": "<b>Deployment Successful</b>\n\n<b>App:</b> {{ .app.metadata.name }}\n<b>Project:</b> {{ .app.spec.project }}\n<b>Revision:</b> <code>{{ .app.status.sync.revision }}</code>\n<b>Namespace:</b> {{ .app.spec.destination.namespace }}\n<b>Health:</b> {{ .app.status.health.status }}"
          }
  
  template.telegram-sync-failed: |
    webhook:
      telegram:
        method: POST
        body: |
          {
            "chat_id": "7537927055",
            "parse_mode": "HTML",
            "disable_web_page_preview": true,
            "text": "SYNC FAILED\n\n<b>Application:</b> {{ .app.metadata.name }}\n<b>Project:</b> {{ .app.spec.project }}\n<b>Revision:</b> <code>{{ .app.status.sync.revision }}</code>\n<b>Namespace:</b> {{ .app.spec.destination.namespace }}\n\n<b>Error:</b>\n<pre>{{ .app.status.operationState.message }}</pre>"
          }

  template.telegram-sync-running: |
    webhook:
      telegram:
        method: POST
        body: |
          {
            "chat_id": "7537927055",
            "parse_mode": "HTML",
            "text": "SYNC RUNNING\n\n<b>Application:</b> {{ .app.metadata.name }}\n<b>Project:</b> {{ .app.spec.project }}\n<b>Namespace:</b> {{ .app.spec.destination.namespace }}"
          }

  # Notification Triggers
  trigger.on-deployed-telegram: |
    - when: app.status != nil and app.status.operationState != nil and app.status.operationState.phase in ['Succeeded'] and app.status.sync.status == 'Synced'
      oncePer: app.status.sync.revision
      send: [telegram-sync-succeeded]
  
  trigger.on-sync-failed-telegram: |
    - when: app.status != nil and app.status.operationState != nil and app.status.operationState.phase in ['Error', 'Failed']
      send: [telegram-sync-failed]

  trigger.on-sync-running-telegram: |
    - when: app.status != nil and app.status.operationState != nil and app.status.operationState.phase in ['Running']
      oncePer: app.status.sync.revision
      send: [telegram-sync-running]
