apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncio-gateway
  namespace: syncio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncio-gateway
  template:
    metadata:
      labels:
        app: syncio-gateway
    spec:
      containers:
        - name: gateway
          image: vietpham18/api-gateway:f23026053781dda463a0df388b27baa547c82e79
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "768Mi"
          env:
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: SPRING_CLOUD_SERVICE_REGISTRY_AUTO_REGISTRATION_ENABLED
              value: "false"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: syncio-gateway
  namespace: syncio
  annotations:
    cloud.google.com/backend-config: '{"default": "syncio-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: syncio-gateway
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: syncio-backend-config
  namespace: syncio
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /actuator/health
    port: 8080
