apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncio-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncio-zookeeper
  template:
    metadata:
      labels:
        app: syncio-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:7.5.0
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: syncio-zookeeper
spec:
  selector:
    app: syncio-zookeeper
  ports:
    - port: 2181

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncio-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncio-kafka
  template:
    metadata:
      labels:
        app: syncio-kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:7.5.0
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: syncio-zookeeper:2181
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://syncio-kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: syncio-kafka
spec:
  selector:
    app: syncio-kafka
  ports:
    - port: 9092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncio-zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncio-zipkin
  template:
    metadata:
      labels:
        app: syncio-zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin:3
          ports:
            - containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: syncio-zipkin
spec:
  selector:
    app: syncio-zipkin
  ports:
    - port: 9411
