apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncio-ingress
  namespace: syncio
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: syncio-ip
    networking.gke.io/managed-certificates: syncio-cert
spec:
  rules:
    - host: syncio.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: syncio-gateway
                port:
                  number: 80