spring.application.name=websocket-service
server.port=8091

# Kafka Configuration
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:syncio-kafka:9092}
spring.kafka.consumer.group-id=websocket-service-group
spring.kafka.consumer.auto-offset-reset=latest

# gRPC Clients
grpc.client.messaging_service.address=dns:///${SYNCIO_MESSAGING_HOST:syncio-messaging}:9090
grpc.client.messaging_service.negotiationType=PLAINTEXT

grpc.client.presence_service.address=dns:///${SYNCIO_PRESENCE_HOST:syncio-presence}:9093
grpc.client.presence_service.negotiationType=PLAINTEXT

grpc.client.call_service.address=dns:///${SYNCIO_CALL_HOST:syncio-call}:9092
grpc.client.call_service.negotiationType=PLAINTEXT

# Observability
management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://syncio-zipkin:9411/api/v2/spans
