apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncio-websocket
  namespace: syncio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncio-websocket
  template:
    metadata:
      labels:
        app: syncio-websocket
    spec:
      containers:
        - name: websocket-service
          image: vietpham18/websocket-service:latest
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "syncio-kafka:9092"
            - name: SYNCIO_MESSAGING_HOST
              value: "syncio-messaging"
            - name: SYNCIO_PRESENCE_HOST
              value: "syncio-presence"
            - name: SYNCIO_CALL_HOST
              value: "syncio-call"
            - name: SYNCIO_USER_HOST
              value: "syncio-user"
            - name: SYNCIO_FRONTEND_URL
              value: "https://syncio.gvn.kr"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "300m"
              memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: syncio-websocket
  namespace: syncio
spec:
  selector:
    app: syncio-websocket
  ports:
    - port: 8091
      targetPort: 8091
