apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncio-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "7537927055"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "7537927055"
    notifications.argoproj.io/subscribe.on-sync-running.telegram: "7537927055"
spec:
  project: default
  source:
    repoURL: git@github.com:Gvn2012/syncio_server.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: syncio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
