spring.application.name=auth-service

server.port=${SERVER_PORT:8081}

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

jwt.secret_key=${JWT_SECRET_KEY:ThisIsAVeryLongSecretKeyThatMustBeAtLeast64CharactersLongForHS512Algorithm}
jwt.access_token_duration=${JWT_ACCESS_TOKEN_DURATION:6000000}
jwt.refresh_token_duration=${JWT_REFRESH_TOKEN_DURATION:2592000000}

management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.spring.web.client.request=true
management.metrics.distribution.percentiles-histogram.spring.web.client.response=true
management.metrics.distribution.percentiles-histogram.spring.cloud.gateway.requests=true

spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=health,info,prometheus
management.tracing.sampling.probability=${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
management.zipkin.tracing.endpoint=${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}